[package]
name = "teki-common"
version = "0.3.0"
authors = ["o2sh <ossama-hjaji@live.fr>"]
edition = "2018"

[dependencies]
vector2d = "2.2.0"
bitflags = "1.2.1"
regex = "1.3.4"
serde_json = "1.0"
counted-array = "0.1.2"
lazy_static = "1.4.0"
array-macro = "1.0.5"